insert into ingrediente(id, nome) values(nextval('ingrediente_seq'), 'Cipolla')
insert into ingrediente(id, nome) values(nextval('ingrediente_seq'), 'Aglio')
insert into ingrediente(id, nome) values(nextval('ingrediente_seq'), 'Pomodoro')
insert into ingrediente(id, nome) values(nextval('ingrediente_seq'), 'Farina')
insert into cuoco(id, data_nascita, cognome, nome) values(nextval('cuoco_seq'), '1965-10-8', 'Cracco', 'Carlo')
insert into ricetta(id, cuoco_id, descrizione, nome) values(nextval('ricetta_seq'), (SELECT id FROM cuoco WHERE nome = 'Carlo'), 'Davvero un bellissimo uovo', 'Uovo')
insert into cuoco(id, data_nascita, cognome, nome) values(nextval('cuoco_seq'), '1962-01-12', 'Barbieri', 'Bruno')
insert into ricetta(id, cuoco_id, descrizione, nome) values(nextval('ricetta_seq'), (SELECT id FROM cuoco WHERE nome = 'Carlo'), 'Ottima pizza, 10/10', 'Pizza')
insert into cuoco(id, data_nascita, cognome, nome) values(nextval('cuoco_seq'), '1975-04-16', 'Cannavacciuolo', 'Antonino')
insert into ricette_ingredienti_quantità (quantità, ingredienti_key, ricetta_id) VALUES (2, (SELECT id FROM ingrediente WHERE nome='Cipolla'), (SELECT id FROM ricetta WHERE nome='Uovo'))
INSERT INTO ricette_ingredienti_quantità (quantità, ingredienti_key, ricetta_id) VALUES (2, (SELECT id FROM ingrediente WHERE nome='Farina'), (SELECT id FROM ricetta WHERE nome='Pizza'))
INSERT INTO ricette_ingredienti_quantità (quantità, ingredienti_key, ricetta_id) VALUES (2, (SELECT id FROM ingrediente WHERE nome='Pomodoro'), (SELECT id FROM ricetta WHERE nome='Pizza'))